services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=blog'
      - 'POSTGRES_USER=secret_user'
      - 'POSTGRES_PASSWORD=s3cr3t_p4ssw0rd'
    ports:
      - '32770:5432'
    networks:
      - db

networks:
    db:
        driver: bridge
